### ISSUE TITLE
not sure

### ISSUE THREAD

**Issue by orbitroom** [bravecollective/bravecollective-intel#4]
I don't know what im missing but dotlan-convert.sh is causing an error on all files when running 

Converting dotlan/Verge_Vendor.svg to dotlan/Verge_Vendor.svg.json ...
Traceback (most recent call last):
  File "./dotlan-json.py", line 61, in <module>
    region = toRegion(id)
  File "./dotlan-json.py", line 46, in toRegion
    id = int(node.getAttribute('id')[3:])
ValueError: invalid literal for int() with base 10: 'Campaign'

**Comment by orbitroom** [comment]
Fixed sent pull request
